name: test
on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "v*"
jobs:
  run_test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.13', '1.14', '1.15', '1.16' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Run test script
        run: go test -coverprofile=coverage.out -v ./... && go tool cover -html=coverage.out -o coverage.html
